#include <FileConstants.au3>
#include <MsgBoxConstants.au3>
#include <FTP.au3>

Global $loc = "C:\Users\default.default-PC\Desktop\d2\WebServer\"

ReadFtpINI()
ReadFileINI()

While 1
ToFtp($File1)
sleep(1000)
ToFtp($File2)
sleep(1000)
ToFtp($File3)
sleep(1000)
ToFtp($File4)
sleep(1000)
ToFtp($File5)
sleep(1000)
ToFtp($File6)
sleep(1000)
ToFtp($File7)
sleep(1000)
ToFtp($File8)
sleep(1000)
ToFtp($File9)
sleep(1000)
ToFtp($File10)
sleep(100)
ToFtp($File11)
sleep(1000)
ToFtp($File12)
sleep(1000)
ToFtp($File13)
sleep(1000)
ToFtp($File14)
sleep(1000)
ToFtp($File15)
sleep(1000)
ToFtp($File16)
sleep(5000)
WEnd

Func ReadFtpINI()
   Global $server = IniRead(@ScriptDir & "\Config.ini", "FTP", "Server", "Default Value")
   sleep(200)
   Global $username = IniRead(@ScriptDir & "\Config.ini", "FTP", "UserName", "Default Value")
   sleep(200)
   Global $pass = IniRead(@ScriptDir & "\Config.ini", "FTP", "Password", "Default Value")
EndFunc

Func ReadFileINI()
   Global $File1 = IniRead(@ScriptDir & "\Config.ini", "FILES", "File1", "Default Value")
   sleep(200)
   Global $File2 = IniRead(@ScriptDir & "\Config.ini", "FILES", "File2", "Default Value")
   sleep(200)
   Global $File3 = IniRead(@ScriptDir & "\Config.ini", "FILES", "File3", "Default Value")
   sleep(200)
   Global $File4 = IniRead(@ScriptDir & "\Config.ini", "FILES", "File4", "Default Value")
   sleep(200)
   Global $File5 = IniRead(@ScriptDir & "\Config.ini", "FILES", "File5", "Default Value")
   sleep(200)
   Global $File6 = IniRead(@ScriptDir & "\Config.ini", "FILES", "File6", "Default Value")
   sleep(200)
   Global $File7 = IniRead(@ScriptDir & "\Config.ini", "FILES", "File7", "Default Value")
   sleep(200)
   Global $File8 = IniRead(@ScriptDir & "\Config.ini", "FILES", "File8", "Default Value")
   sleep(200)
   Global $File9 = IniRead(@ScriptDir & "\Config.ini", "FILES", "File9", "Default Value")
   sleep(200)
   Global $File10 = IniRead(@ScriptDir & "\Config.ini", "FILES", "File10", "Default Value")
   sleep(200)
   Global $File11 = IniRead(@ScriptDir & "\Config.ini", "FILES", "File11", "Default Value")
   sleep(200)
   Global $File12 = IniRead(@ScriptDir & "\Config.ini", "FILES", "File12", "Default Value")
   sleep(200)
   Global $File13 = IniRead(@ScriptDir & "\Config.ini", "FILES", "File13", "Default Value")
   sleep(200)
   Global $File14 = IniRead(@ScriptDir & "\Config.ini", "FILES", "File14", "Default Value")
   sleep(200)
   Global $File15 = IniRead(@ScriptDir & "\Config.ini", "FILES", "File15", "Default Value")
   sleep(200)
   Global $File16 = IniRead(@ScriptDir & "\Config.ini", "FILES", "File16", "Default Value")
EndFunc

Func ToFtp($file)

$Open = _FTPOpen('MyFTP Control')
$Conn = _FTPConnect($Open, $server, $username, $pass)
$Ftpp = _FtpPutFile($Conn,$loc & $file , $file)
$Ftpc = _FTPClose($Open)
EndFunc